# Site settings
title: nononco
email: ""
description: > # this means to ignore newlines until "baseurl:"
  No nonsense communication about functional programming, Racket, compilers,
  interpreters, editors, IDEs and everything else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nononco.com" # the base hostname & protocol for your site
twitter_username: XqrC
github_username:  jpeinelt

# Build settings
markdown: kramdown
